version: '3.8'

services:
  web:
    build: .
    container_name: sentinelvision_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    # A linha abaixo foi adicionada para carregar o arquivo .env
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db/sentinelvision_db
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: sentinelvision_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sentinelvision_db
      - POSTGRES_USER=postgres
      # A senha agora será lida do arquivo .env pelo Docker Compose
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data: