services:
  web:
    build: .
    container_name: sentinelvision_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    # Linha removida
    # environment:
    #   - FLASK_APP=app.py
    #   - DATABASE_URL=postgresql://postgres:admin@db/sentinelvision_db
    # Adicionada esta nova linha
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:16
    container_name: sentinelvision_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sentinelvision_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

volumes:
  postgres_data: